### ISSUE TITLE
unfollow之后，对方依然following

### ISSUE THREAD

**Issue by chinesedfan** [GitMax-CN/GitMax#3]
> 请注意GitMax会自动将你从该好友的follow列表中也删除。

似乎对方没有立即删除，请问同步的机制是什么？GitMax如何知道我unfollow了某人？

**Comment by ChenLi0830** [comment]
Hello, @chinesedfan 这个我们是通过一个scheduled的task对所有人的好友进行比对，如果发现你unfollow了某人，task也会让他unfollow你。这个task暂时是每周运行一次的。所以一周内会帮你完成unfollow

**Comment by chinesedfan** [comment]
哈，和我设想的一样~

因为我没有在本项目找到定时任务相关代码，假设我单方面follow了某用户X，当我和用户X同时成为GitMax用户后，是否一周内定时任务会把我“单相思”的用户X给悄悄unfollow掉？

**Comment by ChenLi0830** [comment]
@chinesedfan 很棒的问题，在unfollow之前需要检查数据库，看你们的好友关系是否由GitMax建立，如果不是，则不会给你unfollow

**Comment by chinesedfan** [comment]
赞，考虑得很周全，谢谢解答~
